---
name: Publish code archive

on:
  release:
    types: # This configuration does not affect the page_build event above
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: archive master branch
        run: |
          git archive HEAD -o archive.tar
          tar -f archive.tar --delete .github
          mkdir code
          tar -xvf archive.tar -C code
      - run: ls *
      - name: deploy to github pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_ARCHIVE }}
          external_repository: cristianpb/test-archive
          publish_branch: code
          publish_dir: code
