---
name: Publish code archive

on:
  release:
    types: # This configuration does not affect the page_build event above
      - published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: archive master branch
        run: |
          git archive HEAD -o archive.tar
          tar -f archive.tar --delete .github
          mkdir code
          tar -xvf archive.tar -C code
      - run: echo $BRANCH
        env:
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
      - name: deploy to github pages
        if: success() && steps.extract_branch.outputs.branch == 'master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY_ARCHIVE }}
          external_repository: cristianpb/test-archive
          publish_branch: code
          publish_dir: code
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
